"""Generate glossary.tex and inject the glossary JSON into the HTML from glossary.json.

Usage: python3 make_glossary.py <slug>
Reads  glossary.json; writes glossary.tex; rewrites the <script id="glossary"> block
in <slug>.html; then checks that every key used in <slug>.html and <slug>.tex exists
and reports keys used in one format but not the other.
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

LATEX_SPECIALS = {
    "\\": r"\textbackslash{}", "&": r"\&", "%": r"\%", "$": r"\$", "#": r"\#",
    "_": r"\_", "{": r"\{", "}": r"\}", "~": r"\textasciitilde{}", "^": r"\textasciicircum{}",
}


def tex_escape(s: str) -> str:
    return "".join(LATEX_SPECIALS.get(c, c) for c in s)


def tex_entry(key: str, e: dict[str, str]) -> str:
    plural = f",\n  plural={{{tex_escape(e['plural'])}}}" if "plural" in e else ""
    return (
        f"\\newglossaryentry{{{key}}}{{\n"
        f"  name={{{tex_escape(e['term'])}}},\n"
        f"  description={{{tex_escape(e['definition'])}}}{plural}\n}}"
    )


def inject_html(html: str, gloss: dict[str, dict[str, str]]) -> str:
    payload = json.dumps(gloss, ensure_ascii=False, indent=1).replace("<", "\\u003c")
    pattern = re.compile(r'(<script type="application/json" id="glossary">)(.*?)(</script>)', re.S)
    if not pattern.search(html):
        sys.exit('error: no <script type="application/json" id="glossary"> block in HTML')
    return pattern.sub(lambda m: f"{m.group(1)}\n{payload}\n{m.group(3)}", html, count=1)


def keys_used(text: str, fmt: str) -> set[str]:
    if fmt == "html":
        return set(re.findall(r'data-g="([^"]+)"', text))
    return set(re.findall(r"\\[gG]ls(?:pl|link|text|first)?\*?(?:\[[^\]]*\])?\{([^}]+)\}", text))


def main(slug: str) -> None:
    gloss: dict[str, dict[str, str]] = json.loads(Path("glossary.json").read_text(encoding="utf-8"))
    Path("glossary.tex").write_text(
        "% Generated by make_glossary.py from glossary.json. Do not edit by hand.\n"
        + "\n".join(tex_entry(k, e) for k, e in sorted(gloss.items())) + "\n",
        encoding="utf-8",
    )
    html_path, tex_path = Path(f"{slug}.html"), Path(f"{slug}.tex")
    html = html_path.read_text(encoding="utf-8")
    html_path.write_text(inject_html(html, gloss), encoding="utf-8")

    used = {"html": keys_used(html, "html"), "tex": keys_used(tex_path.read_text(encoding="utf-8"), "tex")}
    defined = set(gloss)
    problems = [f"{fmt}: undefined key {k!r}" for fmt, ks in used.items() for k in sorted(ks - defined)]
    problems += [f"defined but unused in {fmt}: {k!r}" for fmt, ks in used.items() for k in sorted(defined - ks)]
    problems += [f"used in html only: {k!r}" for k in sorted(used["html"] - used["tex"])]
    problems += [f"used in tex only: {k!r}" for k in sorted(used["tex"] - used["html"])]
    print("\n".join(problems) if problems else f"glossary ok: {len(defined)} terms, parity between html and tex")
    if any(p.startswith(("html: undefined", "tex: undefined")) for p in problems):
        sys.exit(1)


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else sys.exit("usage: make_glossary.py <slug>"))
